================================================================================
-- SINGLE PL/SQL BLOCK EXECUTION
-- Finance Domain | Oracle 21c
-- Operations: DDL (CREATE), DML (INSERT), CONSTRAINTS (ALTER)
================================================================================
SET SERVEROUTPUT ON;
SET DEFINE OFF;

DECLARE
    -- Helper Procedure for DDL (Table Creation)
    PROCEDURE exec_ddl(p_sql IN CLOB, p_desc IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        DBMS_OUTPUT.PUT_LINE('✔ TABLE CREATED: ' || p_desc);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('✖ ERROR creating table ' || p_desc || ': ' || SQLERRM);
            RAISE;
    END exec_ddl;

    -- Helper Procedure for DML (Data Load)
    PROCEDURE exec_dml(p_sql IN CLOB, p_desc IN VARCHAR2) IS
        v_rows NUMBER;
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        v_rows := SQL%ROWCOUNT;
        COMMIT;
        DBMS_OUTPUT.PUT_LINE('✔ DATA LOADED: ' || p_desc || ' (' || v_rows || ' rows inserted)');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('✖ ERROR loading data for ' || p_desc || ': ' || SQLERRM);
            ROLLBACK;
            RAISE;
    END exec_dml;

    -- Helper Procedure for Constraints & Indexes
    PROCEDURE exec_cst(p_sql IN CLOB, p_desc IN VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE p_sql;
        DBMS_OUTPUT.PUT_LINE('  -> Applied: ' || p_desc);
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('  ✖ ERROR applying ' || p_desc || ': ' || SQLERRM);
            RAISE;
    END exec_cst;

BEGIN
    DBMS_OUTPUT.PUT_LINE(RPAD('=', 80, '='));
    DBMS_OUTPUT.PUT_LINE('PHASE 1: DDL (TABLE CREATION)');
    DBMS_OUTPUT.PUT_LINE(RPAD('=', 80, '='));

    exec_ddl(q'[CREATE TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE (
        PROFILE_ID              NUMBER(38)          NOT NULL,
        MEMBER_ID               VARCHAR2(50)        NOT NULL,
        FIRST_NAME              VARCHAR2(100),
        REGION                  VARCHAR2(100),
        TOTAL_TRADES            NUMBER(38)          DEFAULT 0,
        TOTAL_BUY               NUMBER(38)          DEFAULT 0,
        TOTAL_SELL              NUMBER(38)          DEFAULT 0,
        TOTAL_QTY_TRADED        NUMBER(38)          DEFAULT 0,
        AVG_FEE_PERCENTAGE      NUMBER(10,4)        DEFAULT 0,
        FIRST_TXN_DATE          DATE,
        LAST_TXN_DATE           DATE,
        ACTIVE_TICKERS          NUMBER(38)          DEFAULT 0,
        COMPLETED_TXN_COUNT     NUMBER(38)          DEFAULT 0,
        PENDING_TXN_COUNT       NUMBER(38)          DEFAULT 0,
        MAX_TRADE_QTY           NUMBER(38),
        FAVORITE_TICKER         VARCHAR2(20)
    )]', 'BITCOIN_MEMBER_TRADE_PROFILE');

    exec_ddl(q'[CREATE TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS (
        STATS_ID                NUMBER(38)          NOT NULL,
        TICKER                  VARCHAR2(20)        NOT NULL,
        TRADE_DATE              DATE                NOT NULL,
        OPEN_PRICE              NUMBER(38),
        HIGH_PRICE              NUMBER(38),
        LOW_PRICE               NUMBER(38),
        CLOSE_PRICE             NUMBER(38),
        TOTAL_TRADES            NUMBER(38)          DEFAULT 0,
        TOTAL_QTY               NUMBER(38)          DEFAULT 0,
        AVG_FEE                 NUMBER(10,4)        DEFAULT 0,
        TOTAL_BUY_COUNT         NUMBER(38)          DEFAULT 0,
        TOTAL_SELL_COUNT        NUMBER(38)          DEFAULT 0,
        PRICE_CHANGE            VARCHAR2(20),
        PRICE_VOLATILITY_SPREAD NUMBER(38),
        TXN_VOLUME_TIER         VARCHAR2(20)
    )]', 'BITCOIN_DAILY_TRADE_STATS');

    exec_ddl(q'[CREATE TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL (
        DETAIL_ID               NUMBER(38)          NOT NULL,
        CUSTOMER_ID             NUMBER(38)          NOT NULL,
        REGION_ID               NUMBER(38)          NOT NULL,
        REGION_NAME             VARCHAR2(100),
        NODE_ID                 NUMBER(38),
        TXN_TYPE                VARCHAR2(20),
        TXN_AMOUNT              NUMBER(38),
        TXN_DATE                DATE,
        START_DATE              DATE,
        END_DATE                DATE,
        TOTAL_DEPOSITS          NUMBER(38)          DEFAULT 0,
        TXN_COUNT               NUMBER(38)          DEFAULT 0,
        AVG_TXN_AMOUNT          NUMBER(38,2),
        ACTIVE_DAYS_AT_NODE     NUMBER(38)
    )]', 'CUSTOMER_REGION_TXN_DETAIL');

    exec_ddl(q'[CREATE TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY (
        SESSION_ID              NUMBER(38)          NOT NULL,
        USER_ID                 NUMBER(38),
        COOKIE_ID               VARCHAR2(50),
        VISIT_ID                VARCHAR2(50)        NOT NULL,
        TOTAL_EVENTS            NUMBER(38)          DEFAULT 0,
        PAGE_VIEWS              NUMBER(38)          DEFAULT 0,
        ADD_TO_CART_COUNT       NUMBER(38)          DEFAULT 0,
        PURCHASE_COUNT          NUMBER(38)          DEFAULT 0,
        FIRST_EVENT_TIME        TIMESTAMP(6),
        LAST_EVENT_TIME         TIMESTAMP(6),
        DISTINCT_PRODUCTS_VIEWED NUMBER(38)         DEFAULT 0,
        SESSION_DURATION_SECS   NUMBER(38),
        CART_ABANDONMENT_FLAG   CHAR(1),
        AVG_PAGE_VIEWS_PER_EVENT NUMBER(10,2)
    )]', 'SHOPPING_CART_SESSION_SUMMARY');

    exec_ddl(q'[CREATE TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY (
        PROFIT_ID               NUMBER(38)          NOT NULL,
        ITEM_CODE               NUMBER(38)          NOT NULL,
        ITEM_NAME               VARCHAR2(100),
        CATEGORY_CODE           NUMBER(38),
        CATEGORY_NAME           VARCHAR2(100),
        AVG_SELLING_PRICE       NUMBER(10,4),
        AVG_WHOLESALE_PRICE     NUMBER(10,4),
        LOSS_RATE               NUMBER(10,4),
        GROSS_MARGIN_RMB        NUMBER(10,4),
        TOTAL_QTY_SOLD          NUMBER(38)          DEFAULT 0,
        TOTAL_REVENUE           NUMBER(38)          DEFAULT 0,
        TOTAL_DISCOUNTS         NUMBER(10,4)        DEFAULT 0,
        NET_PROFIT_ESTIMATE     NUMBER(38),
        TOTAL_RETURN_QTY        NUMBER(38)          DEFAULT 0,
        PROFIT_MARGIN_PCT       NUMBER(10,4)
    )]', 'VEG_ITEM_PROFIT_SUMMARY');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND (
        TREND_ID                NUMBER(38)          NOT NULL,
        COUNTRY_CODE            VARCHAR2(10)        NOT NULL,
        COUNTRY_NAME            VARCHAR2(100),
        REGION                  VARCHAR2(100),
        INCOME_GROUP            VARCHAR2(50),
        CURRENCY_UNIT           VARCHAR2(50),
        INDICATOR_CODE          VARCHAR2(50),
        INDICATOR_NAME          VARCHAR2(300),
        YEAR                    VARCHAR2(10),
        DEBT_VALUE              NUMBER(38,2),
        PREV_YEAR_DEBT          NUMBER(38,2),
        YOY_CHANGE_VALUE        NUMBER(38,2),
        YOY_CHANGE_PCT          NUMBER(10,4),
        TREND_DIRECTION         VARCHAR2(10)
    )]', 'COUNTRY_DEBT_TREND');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY (
        SUMMARY_ID              NUMBER(38)          NOT NULL,
        REGION                  VARCHAR2(100)       NOT NULL,
        INCOME_GROUP            VARCHAR2(50),
        INDICATOR_CODE          VARCHAR2(50),
        INDICATOR_NAME          VARCHAR2(300),
        YEAR                    VARCHAR2(10),
        TOTAL_DEBT              NUMBER(38,2)        DEFAULT 0,
        AVG_DEBT                NUMBER(38,2)        DEFAULT 0,
        MAX_DEBT                NUMBER(38,2),
        MIN_DEBT                NUMBER(38,2),
        COUNTRY_COUNT           NUMBER(38)          DEFAULT 0,
        DEBT_SPREAD             NUMBER(38,2),
        DISTINCT_INDICATOR_COUNT NUMBER(38)
    )]', 'REGION_INCOME_DEBT_SUMMARY');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN (
        BREAKDOWN_ID            NUMBER(38)          NOT NULL,
        INDICATOR_CODE          VARCHAR2(50)        NOT NULL,
        INDICATOR_NAME          VARCHAR2(300),
        TOPIC                   VARCHAR2(200),
        SHORT_DEFINITION        VARCHAR2(2000),
        UNIT_OF_MEASURE         VARCHAR2(50),
        YEAR                    VARCHAR2(10),
        TOTAL_DEBT              NUMBER(38,2)        DEFAULT 0,
        AVG_DEBT                NUMBER(38,2)        DEFAULT 0,
        COUNTRY_COUNT           NUMBER(38)          DEFAULT 0,
        PERIODICITY             VARCHAR2(20),
        AGGREGATION_METHOD      VARCHAR2(100),
        LICENSE_TYPE            VARCHAR2(4000),
        SOURCE_ORGANIZATION     VARCHAR2(1000)
    )]', 'INDICATOR_DEBT_BREAKDOWN');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE (
        PROFILE_ID              NUMBER(38)          NOT NULL,
        COUNTRY_CODE            VARCHAR2(10)        NOT NULL,
        COUNTRY_NAME            VARCHAR2(100),
        SHORT_NAME              VARCHAR2(100),
        REGION                  VARCHAR2(100),
        INCOME_GROUP            VARCHAR2(50),
        CURRENCY_UNIT           VARCHAR2(50),
        INDICATOR_CODE          VARCHAR2(50),
        TOTAL_DEBT              NUMBER(38,2)        DEFAULT 0,
        AVG_DEBT                NUMBER(38,2)        DEFAULT 0,
        MAX_DEBT_YEAR           VARCHAR2(10),
        MIN_DEBT_YEAR           VARCHAR2(10),
        LENDING_CATEGORY        VARCHAR2(20),
        PPP_SURVEY_YEAR         VARCHAR2(50),
        EXTERNAL_DEBT_STATUS    VARCHAR2(50)
    )]', 'HIGH_DEBT_COUNTRY_PROFILE');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG (
        LOG_ID                  NUMBER(38)          NOT NULL,
        SERIES_CODE             VARCHAR2(50)        NOT NULL,
        COUNTRY_CODE            VARCHAR2(10)        NOT NULL,
        DESCRIPTION             VARCHAR2(1000),
        YEAR                    NUMBER(4),
        TOPIC                   VARCHAR2(200),
        INDICATOR_NAME          VARCHAR2(300),
        UNIT_OF_MEASURE         VARCHAR2(50),
        PERIODICITY             VARCHAR2(20),
        AGGREGATION_METHOD      VARCHAR2(100),
        LAST_RECORDED_YEAR      NUMBER(4),
        BASE_PERIOD             VARCHAR2(50),
        DATA_SOURCE             VARCHAR2(1000)
    )]', 'DEBT_SERIES_ACTIVITY_LOG');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_WDI.COUNTRY_INDICATOR_TREND (
        TREND_ID                NUMBER(38)          NOT NULL,
        COUNTRY_CODE            VARCHAR2(10)        NOT NULL,
        COUNTRY_NAME            VARCHAR2(100),
        REGION                  VARCHAR2(100),
        INCOME_GROUP            VARCHAR2(50),
        INDICATOR_CODE          VARCHAR2(50),
        INDICATOR_NAME          VARCHAR2(500),
        YEAR                    NUMBER(4),
        INDICATOR_VALUE         VARCHAR2(50),
        CURRENCY_UNIT           VARCHAR2(100),
        LENDING_CATEGORY        VARCHAR2(50),
        SNA_PRICE_VALUATION     VARCHAR2(50),
        PREV_YEAR_VALUE         VARCHAR2(50),
        YOY_CHANGE_VALUE        NUMBER(38,4)
    )]', 'COUNTRY_INDICATOR_TREND');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY (
        SUMMARY_ID              NUMBER(38)          NOT NULL,
        REGION                  VARCHAR2(100)       NOT NULL,
        INCOME_GROUP            VARCHAR2(50),
        INDICATOR_CODE          VARCHAR2(50),
        INDICATOR_NAME          VARCHAR2(500),
        YEAR                    NUMBER(4),
        TOTAL_VALUE             NUMBER(38,4),
        AVG_VALUE               NUMBER(38,4),
        MAX_VALUE               NUMBER(38,4),
        MIN_VALUE               NUMBER(38,4),
        COUNTRY_COUNT           NUMBER(38)          DEFAULT 0,
        RECORD_COUNT            NUMBER(38)          DEFAULT 0,
        VALUE_SPREAD            NUMBER(38,4)
    )]', 'REGION_INDICATOR_SUMMARY');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE (
        COVERAGE_ID             NUMBER(38)          NOT NULL,
        SERIES_CODE             VARCHAR2(50)        NOT NULL,
        TOPIC                   VARCHAR2(200),
        INDICATOR_NAME          VARCHAR2(500),
        UNIT_OF_MEASURE         VARCHAR2(100),
        PERIODICITY             VARCHAR2(100),
        TOTAL_COUNTRIES         NUMBER(38)          DEFAULT 0,
        TOTAL_RECORDS           NUMBER(38)          DEFAULT 0,
        AVG_VALUE               NUMBER(38,4),
        DATA_COMPLETENESS_PCT   NUMBER(5,2),
        LICENSE_TYPE            VARCHAR2(4000),
        SOURCE_AGENCY           VARCHAR2(1000),
        BASE_PERIOD             VARCHAR2(50)
    )]', 'SERIES_TOPIC_COVERAGE');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE (
        PROFILE_ID              NUMBER(38)          NOT NULL,
        INCOME_GROUP            VARCHAR2(50)        NOT NULL,
        INDICATOR_CODE          VARCHAR2(50),
        INDICATOR_NAME          VARCHAR2(500),
        YEAR                    NUMBER(4),
        COUNTRY_COUNT           NUMBER(38)          DEFAULT 0,
        AVG_VALUE               NUMBER(38,4),
        MAX_VALUE               NUMBER(38,4),
        MIN_VALUE               NUMBER(38,4),
        TOTAL_VALUE             NUMBER(38,4),
        SERIES_CODE             VARCHAR2(50),
        DISTINCT_REGIONS_COUNT  NUMBER(38),
        VALUE_SPREAD            NUMBER(38,4)
    )]', 'INCOME_GROUP_INDICATOR_PROFILE');

    exec_ddl(q'[CREATE TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT (
        AUDIT_ID                NUMBER(38)          NOT NULL,
        COUNTRY_CODE            VARCHAR2(10)        NOT NULL,
        COUNTRY_NAME            VARCHAR2(100),
        REGION                  VARCHAR2(100),
        INCOME_GROUP            VARCHAR2(50),
        SERIES_CODE             VARCHAR2(50)        NOT NULL,
        INDICATOR_NAME          VARCHAR2(500),
        YEAR                    NUMBER(4),
        INDICATOR_VALUE         VARCHAR2(50),
        FOOTNOTE_DESCRIPTION    VARCHAR2(2000),
        HAS_FOOTNOTE            CHAR(1)             DEFAULT 'N',
        NULL_VALUE_FLAG         CHAR(1)             DEFAULT 'N',
        DATA_SOURCE             VARCHAR2(1000),
        COUNTRY_SPECIAL_NOTES   VARCHAR2(2000),
        CENSUS_DATA_AVAILABLE   CHAR(1)             DEFAULT 'N'
    )]', 'COUNTRY_DATA_QUALITY_AUDIT');


    DBMS_OUTPUT.PUT_LINE(CHR(10) || RPAD('=', 80, '='));
    DBMS_OUTPUT.PUT_LINE('PHASE 2: DML (DATA LOAD)');
    DBMS_OUTPUT.PUT_LINE(RPAD('=', 80, '='));

    exec_dml(q'[INSERT INTO BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE (
        PROFILE_ID, MEMBER_ID, FIRST_NAME, REGION, TOTAL_TRADES, TOTAL_BUY, TOTAL_SELL, 
        TOTAL_QTY_TRADED, AVG_FEE_PERCENTAGE, FIRST_TXN_DATE, LAST_TXN_DATE, ACTIVE_TICKERS, 
        COMPLETED_TXN_COUNT, PENDING_TXN_COUNT, MAX_TRADE_QTY, FAVORITE_TICKER
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY m.MEMBER_ID),
        m.MEMBER_ID, m.FIRST_NAME, m.REGION,
        COUNT(t.TXN_ID),
        SUM(CASE WHEN t.TXN_TYPE = 'BUY'  THEN 1 ELSE 0 END),
        SUM(CASE WHEN t.TXN_TYPE = 'SELL' THEN 1 ELSE 0 END),
        NVL(SUM(t.QUANTITY), 0),
        NVL(AVG(t.PERCENTAGE_FEE), 0),
        MIN(t.TXN_DATE),
        MAX(t.TXN_DATE),
        COUNT(DISTINCT t.TICKER),
        SUM(CASE WHEN t.TXN_STATUS = 'COMPLETED' THEN 1 ELSE 0 END),
        SUM(CASE WHEN t.TXN_STATUS = 'PENDING'   THEN 1 ELSE 0 END),
        MAX(t.QUANTITY),
        STATS_MODE(t.TICKER)
    FROM BANK_SALES_TRADING.BITCOIN_MEMBERS m
    LEFT JOIN BANK_SALES_TRADING.BITCOIN_TRANSACTIONS t ON m.MEMBER_ID = t.MEMBER_ID
    GROUP BY m.MEMBER_ID, m.FIRST_NAME, m.REGION]', 'BITCOIN_MEMBER_TRADE_PROFILE');

    exec_dml(q'[INSERT INTO BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS (
        STATS_ID, TICKER, TRADE_DATE, OPEN_PRICE, HIGH_PRICE, LOW_PRICE, CLOSE_PRICE, 
        TOTAL_TRADES, TOTAL_QTY, AVG_FEE, TOTAL_BUY_COUNT, TOTAL_SELL_COUNT, 
        PRICE_CHANGE, PRICE_VOLATILITY_SPREAD, TXN_VOLUME_TIER
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY p.TICKER, p.MARKET_DATE),
        p.TICKER, p.MARKET_DATE, p.OPEN, p.HIGH, p.LOW, p.PRICE,
        COUNT(t.TXN_ID),
        NVL(SUM(t.QUANTITY), 0),
        NVL(AVG(t.PERCENTAGE_FEE), 0),
        SUM(CASE WHEN t.TXN_TYPE = 'BUY'  THEN 1 ELSE 0 END),
        SUM(CASE WHEN t.TXN_TYPE = 'SELL' THEN 1 ELSE 0 END),
        p.CHANGE,
        (p.HIGH - p.LOW),
        CASE WHEN NVL(SUM(t.QUANTITY), 0) > 1000 THEN 'HIGH' 
             WHEN NVL(SUM(t.QUANTITY), 0) > 100  THEN 'MEDIUM' 
             ELSE 'LOW' END
    FROM BANK_SALES_TRADING.BITCOIN_PRICES p
    LEFT JOIN BANK_SALES_TRADING.BITCOIN_TRANSACTIONS t ON p.TICKER = t.TICKER AND p.MARKET_DATE = t.TXN_DATE
    GROUP BY p.TICKER, p.MARKET_DATE, p.OPEN, p.HIGH, p.LOW, p.PRICE, p.CHANGE]', 'BITCOIN_DAILY_TRADE_STATS');

    exec_dml(q'[INSERT INTO BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL (
        DETAIL_ID, CUSTOMER_ID, REGION_ID, REGION_NAME, NODE_ID, TXN_TYPE, TXN_AMOUNT, 
        TXN_DATE, START_DATE, END_DATE, TOTAL_DEPOSITS, TXN_COUNT, AVG_TXN_AMOUNT, ACTIVE_DAYS_AT_NODE
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY ct.CUSTOMER_ID, ct.TXN_DATE),
        ct.CUSTOMER_ID, cn.REGION_ID, cr.REGION_NAME, cn.NODE_ID, ct.TXN_TYPE, ct.TXN_AMOUNT, 
        ct.TXN_DATE, cn.START_DATE, cn.END_DATE,
        SUM(CASE WHEN ct.TXN_TYPE = 'deposit' THEN ct.TXN_AMOUNT ELSE 0 END) OVER (PARTITION BY ct.CUSTOMER_ID),
        COUNT(ct.CUSTOMER_ID) OVER (PARTITION BY ct.CUSTOMER_ID),
        SUM(CASE WHEN ct.TXN_TYPE = 'deposit' THEN ct.TXN_AMOUNT ELSE 0 END) OVER (PARTITION BY ct.CUSTOMER_ID) / 
            NULLIF(COUNT(ct.CUSTOMER_ID) OVER (PARTITION BY ct.CUSTOMER_ID), 0),
        (cn.END_DATE - cn.START_DATE)
    FROM BANK_SALES_TRADING.CUSTOMER_TRANSACTIONS ct
    LEFT JOIN BANK_SALES_TRADING.CUSTOMER_NODES cn ON ct.CUSTOMER_ID = cn.CUSTOMER_ID AND ct.TXN_DATE BETWEEN cn.START_DATE AND cn.END_DATE
    LEFT JOIN BANK_SALES_TRADING.CUSTOMER_REGIONS cr ON cn.REGION_ID = cr.REGION_ID]', 'CUSTOMER_REGION_TXN_DETAIL');

    exec_dml(q'[INSERT INTO BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY (
        SESSION_ID, USER_ID, COOKIE_ID, VISIT_ID, TOTAL_EVENTS, PAGE_VIEWS, ADD_TO_CART_COUNT, 
        PURCHASE_COUNT, FIRST_EVENT_TIME, LAST_EVENT_TIME, DISTINCT_PRODUCTS_VIEWED, 
        SESSION_DURATION_SECS, CART_ABANDONMENT_FLAG, AVG_PAGE_VIEWS_PER_EVENT
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY e.VISIT_ID),
        u.USER_ID, e.COOKIE_ID, e.VISIT_ID,
        COUNT(e.SEQUENCE_NUMBER),
        SUM(CASE WHEN ei.EVENT_NAME = 'Page View'   THEN 1 ELSE 0 END),
        SUM(CASE WHEN ei.EVENT_NAME = 'Add to Cart' THEN 1 ELSE 0 END),
        SUM(CASE WHEN ei.EVENT_NAME = 'Purchase'    THEN 1 ELSE 0 END),
        MIN(e.EVENT_TIME), MAX(e.EVENT_TIME), COUNT(DISTINCT ph.PRODUCT_ID),
        ROUND((CAST(MAX(e.EVENT_TIME) AS DATE) - CAST(MIN(e.EVENT_TIME) AS DATE)) * 86400),
        CASE WHEN SUM(CASE WHEN ei.EVENT_NAME = 'Add to Cart' THEN 1 ELSE 0 END) > 0 
              AND SUM(CASE WHEN ei.EVENT_NAME = 'Purchase' THEN 1 ELSE 0 END) = 0 
             THEN 'Y' ELSE 'N' END,
        ROUND(SUM(CASE WHEN ei.EVENT_NAME = 'Page View' THEN 1 ELSE 0 END) / NULLIF(COUNT(e.SEQUENCE_NUMBER), 0), 2)
    FROM BANK_SALES_TRADING.SHOPPING_CART_EVENTS e
    LEFT JOIN BANK_SALES_TRADING.SHOPPING_CART_USERS u ON e.COOKIE_ID = u.COOKIE_ID
    LEFT JOIN BANK_SALES_TRADING.SHOPPING_CART_EVENT_IDENTIFIER ei ON e.EVENT_TYPE = ei.EVENT_TYPE
    LEFT JOIN BANK_SALES_TRADING.SHOPPING_CART_PAGE_HIERARCHY ph ON e.PAGE_ID = ph.PAGE_ID
    GROUP BY e.VISIT_ID, u.USER_ID, e.COOKIE_ID]', 'SHOPPING_CART_SESSION_SUMMARY');

    exec_dml(q'[INSERT INTO BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY (
        PROFIT_ID, ITEM_CODE, ITEM_NAME, CATEGORY_CODE, CATEGORY_NAME, AVG_SELLING_PRICE, 
        AVG_WHOLESALE_PRICE, LOSS_RATE, GROSS_MARGIN_RMB, TOTAL_QTY_SOLD, TOTAL_REVENUE, 
        TOTAL_DISCOUNTS, NET_PROFIT_ESTIMATE, TOTAL_RETURN_QTY, PROFIT_MARGIN_PCT
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY vc.ITEM_CODE),
        vc.ITEM_CODE, vc.ITEM_NAME, vc.CATEGORY_CODE, vc.CATEGORY_NAME,
        NVL(AVG(vt.UNIT_SELLING_PX_RMB_KG), 0),
        NVL(AVG(vw.WHSLE_PX_RMB_KG), 0),
        NVL(MAX(vl.LOSS_RATE__), 0),
        (NVL(AVG(vt.UNIT_SELLING_PX_RMB_KG), 0) - NVL(AVG(vw.WHSLE_PX_RMB_KG), 0)),
        NVL(SUM(vt.QTY_SOLD_KG_), 0),
        NVL(SUM(vt.QTY_SOLD_KG_ * vt.UNIT_SELLING_PX_RMB_KG), 0),
        NVL(AVG(vt.DISCOUNT___), 0),
        NVL(SUM(vt.QTY_SOLD_KG_ * (vt.UNIT_SELLING_PX_RMB_KG - NVL(vw.WHSLE_PX_RMB_KG, 0)) * (1 - NVL(vl.LOSS_RATE__, 0) / 100)), 0),
        SUM(CASE WHEN vt.SALE_RETURN IS NOT NULL AND vt.SALE_RETURN != 'No' THEN vt.QTY_SOLD_KG_ ELSE 0 END),
        CASE WHEN NVL(AVG(vt.UNIT_SELLING_PX_RMB_KG), 0) = 0 THEN 0 
             ELSE ROUND((NVL(AVG(vt.UNIT_SELLING_PX_RMB_KG), 0) - NVL(AVG(vw.WHSLE_PX_RMB_KG), 0)) / NVL(AVG(vt.UNIT_SELLING_PX_RMB_KG), 1) * 100, 4) END
    FROM BANK_SALES_TRADING.VEG_CAT vc
    LEFT JOIN BANK_SALES_TRADING.VEG_TXN_DF vt ON vc.ITEM_CODE = vt.ITEM_CODE
    LEFT JOIN BANK_SALES_TRADING.VEG_WHSLE_DF vw ON vc.ITEM_CODE = vw.ITEM_CODE
    LEFT JOIN BANK_SALES_TRADING.VEG_LOSS_RATE_DF vl ON vc.ITEM_CODE = vl.ITEM_CODE
    GROUP BY vc.ITEM_CODE, vc.ITEM_NAME, vc.CATEGORY_CODE, vc.CATEGORY_NAME]', 'VEG_ITEM_PROFIT_SUMMARY');

    exec_dml(q'[INSERT INTO WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND (
        TREND_ID, COUNTRY_CODE, COUNTRY_NAME, REGION, INCOME_GROUP, CURRENCY_UNIT, 
        INDICATOR_CODE, INDICATOR_NAME, YEAR, DEBT_VALUE, PREV_YEAR_DEBT, YOY_CHANGE_VALUE, YOY_CHANGE_PCT, TREND_DIRECTION
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY id.COUNTRY_CODE, id.INDICATOR_CODE, id.YEAR),
        id.COUNTRY_CODE, id.COUNTRY_NAME, cs.REGION, cs.INCOME_GROUP, cs.CURRENCY_UNIT,
        id.INDICATOR_CODE, id.INDICATOR_NAME, id.YEAR, id.VALUE,
        LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR),
        (id.VALUE - LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR)),
        CASE WHEN LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR) IS NULL OR LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR) = 0 THEN NULL
             ELSE ROUND((id.VALUE - LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR)) / LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR) * 100, 4) END,
        CASE WHEN (id.VALUE - LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR)) > 0 THEN 'UP'
             WHEN (id.VALUE - LAG(id.VALUE) OVER (PARTITION BY id.COUNTRY_CODE, id.INDICATOR_CODE ORDER BY id.YEAR)) < 0 THEN 'DOWN' ELSE 'FLAT' END
    FROM WORLD_BANK_INTL_DEBT.INTERNATIONAL_DEBT id
    LEFT JOIN WORLD_BANK_INTL_DEBT.COUNTRY_SUMMARY cs ON id.COUNTRY_CODE = cs.COUNTRY_CODE]', 'COUNTRY_DEBT_TREND');

    exec_dml(q'[INSERT INTO WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY (
        SUMMARY_ID, REGION, INCOME_GROUP, INDICATOR_CODE, INDICATOR_NAME, YEAR, 
        TOTAL_DEBT, AVG_DEBT, MAX_DEBT, MIN_DEBT, COUNTRY_COUNT, DEBT_SPREAD, DISTINCT_INDICATOR_COUNT
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY cs.REGION, cs.INCOME_GROUP, id.INDICATOR_CODE, id.YEAR),
        cs.REGION, cs.INCOME_GROUP, id.INDICATOR_CODE, id.INDICATOR_NAME, id.YEAR,
        SUM(id.VALUE), ROUND(AVG(id.VALUE), 2), MAX(id.VALUE), MIN(id.VALUE),
        COUNT(DISTINCT id.COUNTRY_CODE),
        (MAX(id.VALUE) - MIN(id.VALUE)),
        COUNT(DISTINCT id.INDICATOR_CODE)
    FROM WORLD_BANK_INTL_DEBT.INTERNATIONAL_DEBT id
    INNER JOIN WORLD_BANK_INTL_DEBT.COUNTRY_SUMMARY cs ON id.COUNTRY_CODE = cs.COUNTRY_CODE
    WHERE cs.REGION IS NOT NULL
    GROUP BY cs.REGION, cs.INCOME_GROUP, id.INDICATOR_CODE, id.INDICATOR_NAME, id.YEAR]', 'REGION_INCOME_DEBT_SUMMARY');

    exec_dml(q'[INSERT INTO WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN (
        BREAKDOWN_ID, INDICATOR_CODE, INDICATOR_NAME, TOPIC, SHORT_DEFINITION, UNIT_OF_MEASURE, 
        YEAR, TOTAL_DEBT, AVG_DEBT, COUNTRY_COUNT, PERIODICITY, AGGREGATION_METHOD, LICENSE_TYPE, SOURCE_ORGANIZATION
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY id.INDICATOR_CODE, id.YEAR),
        id.INDICATOR_CODE, id.INDICATOR_NAME, ss.TOPIC, ss.SHORT_DEFINITION, ss.UNIT_OF_MEASURE,
        id.YEAR, SUM(id.VALUE), ROUND(AVG(id.VALUE), 2), COUNT(DISTINCT id.COUNTRY_CODE),
        ss.PERIODICITY, ss.AGGREGATION_METHOD, 
        MAX(ss.LICENSE_TYPE), MAX(SUBSTR(ss.SOURCE, 1, 1000))
    FROM WORLD_BANK_INTL_DEBT.INTERNATIONAL_DEBT id
    LEFT JOIN WORLD_BANK_INTL_DEBT.SERIES_SUMMARY ss ON id.INDICATOR_CODE = ss.SERIES_CODE
    GROUP BY id.INDICATOR_CODE, id.INDICATOR_NAME, ss.TOPIC, ss.SHORT_DEFINITION, ss.UNIT_OF_MEASURE, id.YEAR, ss.PERIODICITY, ss.AGGREGATION_METHOD]', 'INDICATOR_DEBT_BREAKDOWN');

    exec_dml(q'[INSERT INTO WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE (
        PROFILE_ID, COUNTRY_CODE, COUNTRY_NAME, SHORT_NAME, REGION, INCOME_GROUP, 
        CURRENCY_UNIT, INDICATOR_CODE, TOTAL_DEBT, AVG_DEBT, MAX_DEBT_YEAR, MIN_DEBT_YEAR, 
        LENDING_CATEGORY, PPP_SURVEY_YEAR, EXTERNAL_DEBT_STATUS
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY SUM(id.VALUE) DESC),
        id.COUNTRY_CODE, id.COUNTRY_NAME, cs.SHORT_NAME, cs.REGION, cs.INCOME_GROUP,
        cs.CURRENCY_UNIT, id.INDICATOR_CODE, SUM(id.VALUE), ROUND(AVG(id.VALUE), 2),
        MAX(id.YEAR) KEEP (DENSE_RANK LAST  ORDER BY id.VALUE),
        MAX(id.YEAR) KEEP (DENSE_RANK FIRST ORDER BY id.VALUE),
        cs.LENDING_CATEGORY, cs.PPP_SURVEY_YEAR, cs.EXTERNAL_DEBT_REPORTING_STATUS
    FROM WORLD_BANK_INTL_DEBT.INTERNATIONAL_DEBT id
    LEFT JOIN WORLD_BANK_INTL_DEBT.COUNTRY_SUMMARY cs ON id.COUNTRY_CODE = cs.COUNTRY_CODE
    GROUP BY id.COUNTRY_CODE, id.COUNTRY_NAME, cs.SHORT_NAME, cs.REGION, cs.INCOME_GROUP, 
             cs.CURRENCY_UNIT, id.INDICATOR_CODE, cs.LENDING_CATEGORY, cs.PPP_SURVEY_YEAR, cs.EXTERNAL_DEBT_REPORTING_STATUS]', 'HIGH_DEBT_COUNTRY_PROFILE');

    exec_dml(q'[INSERT INTO WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG (
        LOG_ID, SERIES_CODE, COUNTRY_CODE, DESCRIPTION, YEAR, TOPIC, INDICATOR_NAME, 
        UNIT_OF_MEASURE, PERIODICITY, AGGREGATION_METHOD, LAST_RECORDED_YEAR, BASE_PERIOD, DATA_SOURCE
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY csd.COUNTRY_CODE, csd.SERIES_CODE),
        csd.SERIES_CODE, csd.COUNTRY_CODE, csd.DESCRIPTION, st.YEAR, ss.TOPIC, ss.INDICATOR_NAME,
        ss.UNIT_OF_MEASURE, ss.PERIODICITY, ss.AGGREGATION_METHOD, 
        MAX(st.YEAR) OVER (PARTITION BY csd.SERIES_CODE),
        ss.BASE_PERIOD, SUBSTR(ss.SOURCE, 1, 1000)
    FROM WORLD_BANK_INTL_DEBT.COUNTRY_SERIES_DEFINITIONS csd
    LEFT JOIN WORLD_BANK_INTL_DEBT.SERIES_TIMES st ON csd.SERIES_CODE = st.SERIES_CODE
    LEFT JOIN WORLD_BANK_INTL_DEBT.SERIES_SUMMARY ss ON csd.SERIES_CODE = ss.SERIES_CODE]', 'DEBT_SERIES_ACTIVITY_LOG');

    exec_dml(q'[INSERT INTO WORLD_BANK_WDI.COUNTRY_INDICATOR_TREND (
        TREND_ID, COUNTRY_CODE, COUNTRY_NAME, REGION, INCOME_GROUP, INDICATOR_CODE, 
        INDICATOR_NAME, YEAR, INDICATOR_VALUE, CURRENCY_UNIT, LENDING_CATEGORY, 
        SNA_PRICE_VALUATION, PREV_YEAR_VALUE, YOY_CHANGE_VALUE
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY ind.COUNTRY_CODE, ind.INDICATOR_CODE, ind.YEAR),
        ind.COUNTRY_CODE, ind.COUNTRY_NAME, cs.REGION, cs.INCOME_GROUP, ind.INDICATOR_CODE,
        ind.INDICATOR_NAME, ind.YEAR, ind.VALUE, cs.CURRENCY_UNIT, cs.LENDING_CATEGORY, cs.SNA_PRICE_VALUATION,
        LAG(ind.VALUE) OVER (PARTITION BY ind.COUNTRY_CODE, ind.INDICATOR_CODE ORDER BY ind.YEAR),
        CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') AND 
                  REGEXP_LIKE(LAG(ind.VALUE) OVER (PARTITION BY ind.COUNTRY_CODE, ind.INDICATOR_CODE ORDER BY ind.YEAR), '^\-?[0-9]+(\.[0-9]+)?$') 
             THEN TO_NUMBER(ind.VALUE) - TO_NUMBER(LAG(ind.VALUE) OVER (PARTITION BY ind.COUNTRY_CODE, ind.INDICATOR_CODE ORDER BY ind.YEAR)) 
             ELSE NULL END
    FROM WORLD_BANK_WDI.INDICATORS_DATA ind
    LEFT JOIN WORLD_BANK_WDI.COUNTRY_SUMMARY cs ON ind.COUNTRY_CODE = cs.COUNTRY_CODE]', 'COUNTRY_INDICATOR_TREND');

    exec_dml(q'[INSERT INTO WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY (
        SUMMARY_ID, REGION, INCOME_GROUP, INDICATOR_CODE, INDICATOR_NAME, YEAR, 
        TOTAL_VALUE, AVG_VALUE, MAX_VALUE, MIN_VALUE, COUNTRY_COUNT, RECORD_COUNT, VALUE_SPREAD
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY cs.REGION, ind.INDICATOR_CODE, ind.YEAR),
        cs.REGION, cs.INCOME_GROUP, ind.INDICATOR_CODE, ind.INDICATOR_NAME, ind.YEAR,
        SUM(TO_NUMBER(ind.VALUE)), ROUND(AVG(TO_NUMBER(ind.VALUE)), 4), 
        MAX(TO_NUMBER(ind.VALUE)), MIN(TO_NUMBER(ind.VALUE)), COUNT(DISTINCT ind.COUNTRY_CODE),
        COUNT(ind.VALUE),
        (MAX(TO_NUMBER(ind.VALUE)) - MIN(TO_NUMBER(ind.VALUE)))
    FROM WORLD_BANK_WDI.INDICATORS_DATA ind
    INNER JOIN WORLD_BANK_WDI.COUNTRY_SUMMARY cs ON ind.COUNTRY_CODE = cs.COUNTRY_CODE
    WHERE cs.REGION IS NOT NULL AND REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$')
    GROUP BY cs.REGION, cs.INCOME_GROUP, ind.INDICATOR_CODE, ind.INDICATOR_NAME, ind.YEAR]', 'REGION_INDICATOR_SUMMARY');

    exec_dml(q'[INSERT INTO WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE (
        COVERAGE_ID, SERIES_CODE, TOPIC, INDICATOR_NAME, UNIT_OF_MEASURE, PERIODICITY, 
        TOTAL_COUNTRIES, TOTAL_RECORDS, AVG_VALUE, DATA_COMPLETENESS_PCT, LICENSE_TYPE, SOURCE_AGENCY, BASE_PERIOD
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY ss.SERIES_CODE),
        ss.SERIES_CODE, ss.TOPIC, ss.INDICATOR_NAME, ss.UNIT_OF_MEASURE, ss.PERIODICITY,
        COUNT(DISTINCT ind.COUNTRY_CODE), COUNT(ind.VALUE),
        ROUND(AVG(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE NULL END), 4),
        ROUND(COUNT(CASE WHEN ind.VALUE IS NOT NULL THEN 1 END) * 100.0 / NULLIF(COUNT(*), 0), 2),
        ss.LICENSE_TYPE, MAX(SUBSTR(ss.SOURCE, 1, 1000)), MAX(ss.BASE_PERIOD)
    FROM WORLD_BANK_WDI.SERIES_SUMMARY ss
    LEFT JOIN WORLD_BANK_WDI.INDICATORS_DATA ind ON ss.SERIES_CODE = ind.INDICATOR_CODE
    GROUP BY ss.SERIES_CODE, ss.TOPIC, ss.INDICATOR_NAME, ss.UNIT_OF_MEASURE, ss.PERIODICITY, ss.LICENSE_TYPE]', 'SERIES_TOPIC_COVERAGE');

    exec_dml(q'[INSERT INTO WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE (
        PROFILE_ID, INCOME_GROUP, INDICATOR_CODE, INDICATOR_NAME, YEAR, COUNTRY_COUNT, 
        AVG_VALUE, MAX_VALUE, MIN_VALUE, TOTAL_VALUE, SERIES_CODE, DISTINCT_REGIONS_COUNT, VALUE_SPREAD
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY cs.INCOME_GROUP, ind.INDICATOR_CODE, ind.YEAR),
        cs.INCOME_GROUP, ind.INDICATOR_CODE, ind.INDICATOR_NAME, ind.YEAR, COUNT(DISTINCT ind.COUNTRY_CODE),
        ROUND(AVG(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE NULL END), 4),
        MAX(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE NULL END),
        MIN(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE NULL END),
        SUM(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE 0 END),
        ind.INDICATOR_CODE, COUNT(DISTINCT cs.REGION),
        (MAX(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE NULL END) - 
         MIN(CASE WHEN REGEXP_LIKE(ind.VALUE, '^\-?[0-9]+(\.[0-9]+)?$') THEN TO_NUMBER(ind.VALUE) ELSE NULL END))
    FROM WORLD_BANK_WDI.INDICATORS_DATA ind
    INNER JOIN WORLD_BANK_WDI.COUNTRY_SUMMARY cs ON ind.COUNTRY_CODE = cs.COUNTRY_CODE
    WHERE cs.INCOME_GROUP IS NOT NULL
    GROUP BY cs.INCOME_GROUP, ind.INDICATOR_CODE, ind.INDICATOR_NAME, ind.YEAR]', 'INCOME_GROUP_INDICATOR_PROFILE');

    exec_dml(q'[INSERT INTO WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT (
        AUDIT_ID, COUNTRY_CODE, COUNTRY_NAME, REGION, INCOME_GROUP, SERIES_CODE, 
        INDICATOR_NAME, YEAR, INDICATOR_VALUE, FOOTNOTE_DESCRIPTION, HAS_FOOTNOTE, 
        NULL_VALUE_FLAG, DATA_SOURCE, COUNTRY_SPECIAL_NOTES, CENSUS_DATA_AVAILABLE
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY ind.COUNTRY_CODE, ind.INDICATOR_CODE, ind.YEAR),
        ind.COUNTRY_CODE, ind.COUNTRY_NAME, cs.REGION, cs.INCOME_GROUP, ind.INDICATOR_CODE,
        ind.INDICATOR_NAME, ind.YEAR, ind.VALUE, fn.DESCRIPTION,
        CASE WHEN fn.DESCRIPTION IS NOT NULL THEN 'Y' ELSE 'N' END,
        CASE WHEN ind.VALUE IS NULL THEN 'Y' ELSE 'N' END,
        SUBSTR(ss.SOURCE, 1, 1000), SUBSTR(cs.SPECIAL_NOTES, 1, 2000),
        CASE WHEN cs.LATEST_POPULATION_CENSUS IS NOT NULL THEN 'Y' ELSE 'N' END
    FROM WORLD_BANK_WDI.INDICATORS_DATA ind
    LEFT JOIN WORLD_BANK_WDI.COUNTRY_SUMMARY cs ON ind.COUNTRY_CODE = cs.COUNTRY_CODE
    LEFT JOIN WORLD_BANK_WDI.FOOTNOTES fn ON ind.COUNTRY_CODE = fn.COUNTRY_CODE AND ind.INDICATOR_CODE = fn.SERIES_CODE AND ind.YEAR = fn.YEAR
    LEFT JOIN WORLD_BANK_WDI.SERIES_SUMMARY ss ON ind.INDICATOR_CODE = ss.SERIES_CODE]', 'COUNTRY_DATA_QUALITY_AUDIT');


    DBMS_OUTPUT.PUT_LINE(CHR(10) || RPAD('=', 80, '='));
    DBMS_OUTPUT.PUT_LINE('PHASE 3: CONSTRAINTS & INDEXES');
    DBMS_OUTPUT.PUT_LINE(RPAD('=', 80, '='));

    -- TABLE 1: BITCOIN_MEMBER_TRADE_PROFILE
    DBMS_OUTPUT.PUT_LINE('TABLE: BITCOIN_MEMBER_TRADE_PROFILE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT PK_BTC_MEMBER_TRADE_PROFILE PRIMARY KEY (PROFILE_ID)]', 'PK_BTC_MEMBER_TRADE_PROFILE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT FK_BTC_MEMBER_PROFILE_MBR FOREIGN KEY (MEMBER_ID) REFERENCES BANK_SALES_TRADING.BITCOIN_MEMBERS (MEMBER_ID)]', 'FK_BTC_MEMBER_PROFILE_MBR');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT UQ_BTC_MEMBER_PROFILE_MBR_ID UNIQUE (MEMBER_ID)]', 'UQ_BTC_MEMBER_PROFILE_MBR_ID');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT CHK_BTC_MEMBER_PROFILE_TRADES CHECK (TOTAL_TRADES >= 0)]', 'CHK_BTC_MEMBER_PROFILE_TRADES');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT CHK_BTC_MEMBER_PROFILE_QTY CHECK (TOTAL_QTY_TRADED >= 0)]', 'CHK_BTC_MEMBER_PROFILE_QTY');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT CHK_BTC_MEMBER_PROFILE_FEE CHECK (AVG_FEE_PERCENTAGE >= 0)]', 'CHK_BTC_MEMBER_PROFILE_FEE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_MEMBER_TRADE_PROFILE ADD CONSTRAINT CHK_BTC_MEMBER_MAX_QTY CHECK (MAX_TRADE_QTY IS NULL OR MAX_TRADE_QTY >= 0)]', 'CHK_BTC_MEMBER_MAX_QTY');

    -- TABLE 2: BITCOIN_DAILY_TRADE_STATS
    DBMS_OUTPUT.PUT_LINE('TABLE: BITCOIN_DAILY_TRADE_STATS');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT PK_BTC_DAILY_TRADE_STATS PRIMARY KEY (STATS_ID)]', 'PK_BTC_DAILY_TRADE_STATS');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT UQ_BTC_DAILY_STATS_TICKER_DATE UNIQUE (TICKER, TRADE_DATE)]', 'UQ_BTC_DAILY_STATS_TICKER_DATE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT FK_BTC_DAILY_STATS_PRICES FOREIGN KEY (TICKER, TRADE_DATE) REFERENCES BANK_SALES_TRADING.BITCOIN_PRICES (TICKER, MARKET_DATE)]', 'FK_BTC_DAILY_STATS_PRICES');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT CHK_BTC_DAILY_STATS_QTY CHECK (TOTAL_QTY >= 0)]', 'CHK_BTC_DAILY_STATS_QTY');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT CHK_BTC_DAILY_STATS_TRADES CHECK (TOTAL_TRADES >= 0)]', 'CHK_BTC_DAILY_STATS_TRADES');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT CHK_BTC_DAILY_STATS_PRICE_RNG CHECK (HIGH_PRICE >= LOW_PRICE OR HIGH_PRICE IS NULL OR LOW_PRICE IS NULL)]', 'CHK_BTC_DAILY_STATS_PRICE_RNG');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.BITCOIN_DAILY_TRADE_STATS ADD CONSTRAINT CHK_BTC_DAILY_VOL_TIER CHECK (TXN_VOLUME_TIER IN ('HIGH', 'MEDIUM', 'LOW') OR TXN_VOLUME_TIER IS NULL)]', 'CHK_BTC_DAILY_VOL_TIER');

    -- TABLE 3: CUSTOMER_REGION_TXN_DETAIL
    DBMS_OUTPUT.PUT_LINE('TABLE: CUSTOMER_REGION_TXN_DETAIL');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL ADD CONSTRAINT PK_CUST_REGION_TXN_DETAIL PRIMARY KEY (DETAIL_ID)]', 'PK_CUST_REGION_TXN_DETAIL');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL ADD CONSTRAINT FK_CUST_REGION_TXN_REGION FOREIGN KEY (REGION_ID) REFERENCES BANK_SALES_TRADING.CUSTOMER_REGIONS (REGION_ID)]', 'FK_CUST_REGION_TXN_REGION');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL ADD CONSTRAINT CHK_CUST_REGION_TXN_AMOUNT CHECK (TXN_AMOUNT >= 0)]', 'CHK_CUST_REGION_TXN_AMOUNT');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL ADD CONSTRAINT CHK_CUST_REGION_TXN_DEPOSITS CHECK (TOTAL_DEPOSITS >= 0)]', 'CHK_CUST_REGION_TXN_DEPOSITS');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL ADD CONSTRAINT CHK_CUST_REGION_TXN_DATES CHECK (END_DATE IS NULL OR START_DATE IS NULL OR END_DATE >= START_DATE)]', 'CHK_CUST_REGION_TXN_DATES');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.CUSTOMER_REGION_TXN_DETAIL ADD CONSTRAINT CHK_CUST_REGION_ACTIVE_DAYS CHECK (ACTIVE_DAYS_AT_NODE IS NULL OR ACTIVE_DAYS_AT_NODE >= 0)]', 'CHK_CUST_REGION_ACTIVE_DAYS');

    -- TABLE 4: SHOPPING_CART_SESSION_SUMMARY
    DBMS_OUTPUT.PUT_LINE('TABLE: SHOPPING_CART_SESSION_SUMMARY');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT PK_SC_SESSION_SUMMARY PRIMARY KEY (SESSION_ID)]', 'PK_SC_SESSION_SUMMARY');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT UQ_SC_SESSION_VISIT_ID UNIQUE (VISIT_ID)]', 'UQ_SC_SESSION_VISIT_ID');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT CHK_SC_SESSION_EVENTS CHECK (TOTAL_EVENTS >= 0)]', 'CHK_SC_SESSION_EVENTS');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT CHK_SC_SESSION_PAGE_VIEWS CHECK (PAGE_VIEWS >= 0)]', 'CHK_SC_SESSION_PAGE_VIEWS');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT CHK_SC_SESSION_DURATION CHECK (SESSION_DURATION_SECS IS NULL OR SESSION_DURATION_SECS >= 0)]', 'CHK_SC_SESSION_DURATION');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT CHK_SC_SESSION_TIMES CHECK (LAST_EVENT_TIME IS NULL OR FIRST_EVENT_TIME IS NULL OR LAST_EVENT_TIME >= FIRST_EVENT_TIME)]', 'CHK_SC_SESSION_TIMES');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.SHOPPING_CART_SESSION_SUMMARY ADD CONSTRAINT CHK_SC_SESSION_ABANDON_FLAG CHECK (CART_ABANDONMENT_FLAG IN ('Y', 'N') OR CART_ABANDONMENT_FLAG IS NULL)]', 'CHK_SC_SESSION_ABANDON_FLAG');

    -- TABLE 5: VEG_ITEM_PROFIT_SUMMARY
    DBMS_OUTPUT.PUT_LINE('TABLE: VEG_ITEM_PROFIT_SUMMARY');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT PK_VEG_ITEM_PROFIT_SUMMARY PRIMARY KEY (PROFIT_ID)]', 'PK_VEG_ITEM_PROFIT_SUMMARY');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT UQ_VEG_ITEM_PROFIT_ITEM_CODE UNIQUE (ITEM_CODE)]', 'UQ_VEG_ITEM_PROFIT_ITEM_CODE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT FK_VEG_ITEM_PROFIT_CAT FOREIGN KEY (ITEM_CODE) REFERENCES BANK_SALES_TRADING.VEG_CAT (ITEM_CODE)]', 'FK_VEG_ITEM_PROFIT_CAT');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT CHK_VEG_ITEM_QTY_SOLD CHECK (TOTAL_QTY_SOLD >= 0)]', 'CHK_VEG_ITEM_QTY_SOLD');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT CHK_VEG_ITEM_REVENUE CHECK (TOTAL_REVENUE >= 0)]', 'CHK_VEG_ITEM_REVENUE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT CHK_VEG_ITEM_LOSS_RATE CHECK (LOSS_RATE IS NULL OR (LOSS_RATE >= 0 AND LOSS_RATE <= 100))]', 'CHK_VEG_ITEM_LOSS_RATE');
    exec_cst(q'[ALTER TABLE BANK_SALES_TRADING.VEG_ITEM_PROFIT_SUMMARY ADD CONSTRAINT CHK_VEG_ITEM_RETURN_QTY CHECK (TOTAL_RETURN_QTY >= 0)]', 'CHK_VEG_ITEM_RETURN_QTY');

    -- TABLE 6: COUNTRY_DEBT_TREND
    DBMS_OUTPUT.PUT_LINE('TABLE: COUNTRY_DEBT_TREND');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND ADD CONSTRAINT PK_COUNTRY_DEBT_TREND PRIMARY KEY (TREND_ID)]', 'PK_COUNTRY_DEBT_TREND');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND ADD CONSTRAINT FK_COUNTRY_DEBT_TREND_CS FOREIGN KEY (COUNTRY_CODE) REFERENCES WORLD_BANK_INTL_DEBT.COUNTRY_SUMMARY (COUNTRY_CODE)]', 'FK_COUNTRY_DEBT_TREND_CS');
    exec_cst(q'[CREATE INDEX WORLD_BANK_INTL_DEBT.IDX_COUNTRY_DEBT_TREND_KEY ON WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND (COUNTRY_CODE, INDICATOR_CODE, YEAR)]', 'IDX_COUNTRY_DEBT_TREND_KEY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND ADD CONSTRAINT CHK_COUNTRY_DEBT_TREND_VALUE CHECK (DEBT_VALUE IS NULL OR DEBT_VALUE >= 0)]', 'CHK_COUNTRY_DEBT_TREND_VALUE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.COUNTRY_DEBT_TREND ADD CONSTRAINT CHK_COUNTRY_DEBT_DIRECTION CHECK (TREND_DIRECTION IN ('UP', 'DOWN', 'FLAT') OR TREND_DIRECTION IS NULL)]', 'CHK_COUNTRY_DEBT_DIRECTION');

    -- TABLE 7: REGION_INCOME_DEBT_SUMMARY
    DBMS_OUTPUT.PUT_LINE('TABLE: REGION_INCOME_DEBT_SUMMARY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY ADD CONSTRAINT PK_REGION_INCOME_DEBT_SUMMARY PRIMARY KEY (SUMMARY_ID)]', 'PK_REGION_INCOME_DEBT_SUMMARY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY ADD CONSTRAINT UQ_REGION_INCOME_DEBT_KEY UNIQUE (REGION, INCOME_GROUP, INDICATOR_CODE, YEAR)]', 'UQ_REGION_INCOME_DEBT_KEY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY ADD CONSTRAINT CHK_REGION_INC_DEBT_TOTAL CHECK (TOTAL_DEBT IS NULL OR TOTAL_DEBT >= 0)]', 'CHK_REGION_INC_DEBT_TOTAL');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY ADD CONSTRAINT CHK_REGION_INC_DEBT_COUNT CHECK (COUNTRY_COUNT >= 0)]', 'CHK_REGION_INC_DEBT_COUNT');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.REGION_INCOME_DEBT_SUMMARY ADD CONSTRAINT CHK_REGION_INC_DEBT_MAXMIN CHECK (MAX_DEBT IS NULL OR MIN_DEBT IS NULL OR MAX_DEBT >= MIN_DEBT)]', 'CHK_REGION_INC_DEBT_MAXMIN');

    -- TABLE 8: INDICATOR_DEBT_BREAKDOWN
    DBMS_OUTPUT.PUT_LINE('TABLE: INDICATOR_DEBT_BREAKDOWN');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN ADD CONSTRAINT PK_INDICATOR_DEBT_BREAKDOWN PRIMARY KEY (BREAKDOWN_ID)]', 'PK_INDICATOR_DEBT_BREAKDOWN');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN ADD CONSTRAINT FK_INDICATOR_DEBT_SERIES FOREIGN KEY (INDICATOR_CODE) REFERENCES WORLD_BANK_INTL_DEBT.SERIES_SUMMARY (SERIES_CODE) NOVALIDATE]', 'FK_INDICATOR_DEBT_SERIES');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN ADD CONSTRAINT UQ_INDICATOR_DEBT_CODE_YEAR UNIQUE (INDICATOR_CODE, YEAR)]', 'UQ_INDICATOR_DEBT_CODE_YEAR');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN ADD CONSTRAINT CHK_INDICATOR_DEBT_TOTAL CHECK (TOTAL_DEBT IS NULL OR TOTAL_DEBT >= 0)]', 'CHK_INDICATOR_DEBT_TOTAL');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.INDICATOR_DEBT_BREAKDOWN ADD CONSTRAINT CHK_INDICATOR_DEBT_COUNT CHECK (COUNTRY_COUNT >= 0)]', 'CHK_INDICATOR_DEBT_COUNT');

    -- TABLE 9: HIGH_DEBT_COUNTRY_PROFILE
    DBMS_OUTPUT.PUT_LINE('TABLE: HIGH_DEBT_COUNTRY_PROFILE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE ADD CONSTRAINT PK_HIGH_DEBT_COUNTRY_PROFILE PRIMARY KEY (PROFILE_ID)]', 'PK_HIGH_DEBT_COUNTRY_PROFILE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE ADD CONSTRAINT FK_HIGH_DEBT_COUNTRY_CS FOREIGN KEY (COUNTRY_CODE) REFERENCES WORLD_BANK_INTL_DEBT.COUNTRY_SUMMARY (COUNTRY_CODE)]', 'FK_HIGH_DEBT_COUNTRY_CS');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE ADD CONSTRAINT UQ_HIGH_DEBT_COUNTRY_KEY UNIQUE (COUNTRY_CODE, INDICATOR_CODE)]', 'UQ_HIGH_DEBT_COUNTRY_KEY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE ADD CONSTRAINT CHK_HIGH_DEBT_TOTAL CHECK (TOTAL_DEBT IS NULL OR TOTAL_DEBT >= 0)]', 'CHK_HIGH_DEBT_TOTAL');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.HIGH_DEBT_COUNTRY_PROFILE ADD CONSTRAINT CHK_HIGH_DEBT_AVG CHECK (AVG_DEBT IS NULL OR AVG_DEBT >= 0)]', 'CHK_HIGH_DEBT_AVG');

    -- TABLE 10: DEBT_SERIES_ACTIVITY_LOG
    DBMS_OUTPUT.PUT_LINE('TABLE: DEBT_SERIES_ACTIVITY_LOG');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG ADD CONSTRAINT PK_DEBT_SERIES_ACTIVITY_LOG PRIMARY KEY (LOG_ID)]', 'PK_DEBT_SERIES_ACTIVITY_LOG');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG ADD CONSTRAINT FK_DEBT_SERIES_LOG_COUNTRY FOREIGN KEY (COUNTRY_CODE) REFERENCES WORLD_BANK_INTL_DEBT.COUNTRY_SUMMARY (COUNTRY_CODE)]', 'FK_DEBT_SERIES_LOG_COUNTRY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG ADD CONSTRAINT FK_DEBT_SERIES_LOG_SERIES FOREIGN KEY (SERIES_CODE) REFERENCES WORLD_BANK_INTL_DEBT.SERIES_SUMMARY (SERIES_CODE)]', 'FK_DEBT_SERIES_LOG_SERIES');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG ADD CONSTRAINT CHK_DEBT_SERIES_LOG_YEAR CHECK (YEAR IS NULL OR YEAR BETWEEN 1900 AND 2100)]', 'CHK_DEBT_SERIES_LOG_YEAR');
    exec_cst(q'[ALTER TABLE WORLD_BANK_INTL_DEBT.DEBT_SERIES_ACTIVITY_LOG ADD CONSTRAINT CHK_DEBT_SERIES_LAST_YEAR CHECK (LAST_RECORDED_YEAR IS NULL OR LAST_RECORDED_YEAR BETWEEN 1900 AND 2100)]', 'CHK_DEBT_SERIES_LAST_YEAR');

    -- TABLE 11: COUNTRY_INDICATOR_TREND
    DBMS_OUTPUT.PUT_LINE('TABLE: COUNTRY_INDICATOR_TREND');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_INDICATOR_TREND ADD CONSTRAINT PK_WDI_COUNTRY_INDICATOR_TREND PRIMARY KEY (TREND_ID)]', 'PK_WDI_COUNTRY_INDICATOR_TREND');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_INDICATOR_TREND ADD CONSTRAINT FK_WDI_CNTRY_IND_TREND_CS FOREIGN KEY (COUNTRY_CODE) REFERENCES WORLD_BANK_WDI.COUNTRY_SUMMARY (COUNTRY_CODE)]', 'FK_WDI_CNTRY_IND_TREND_CS');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_INDICATOR_TREND ADD CONSTRAINT UQ_WDI_CNTRY_IND_TREND_KEY UNIQUE (COUNTRY_CODE, INDICATOR_CODE, YEAR)]', 'UQ_WDI_CNTRY_IND_TREND_KEY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_INDICATOR_TREND ADD CONSTRAINT CHK_WDI_CNTRY_IND_YEAR CHECK (YEAR IS NULL OR YEAR BETWEEN 1900 AND 2100)]', 'CHK_WDI_CNTRY_IND_YEAR');

    -- TABLE 12: REGION_INDICATOR_SUMMARY
    DBMS_OUTPUT.PUT_LINE('TABLE: REGION_INDICATOR_SUMMARY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY ADD CONSTRAINT PK_WDI_REGION_INDICATOR_SUMMARY PRIMARY KEY (SUMMARY_ID)]', 'PK_WDI_REGION_INDICATOR_SUMMARY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY ADD CONSTRAINT UQ_WDI_REGION_IND_SUM_KEY UNIQUE (REGION, INCOME_GROUP, INDICATOR_CODE, YEAR)]', 'UQ_WDI_REGION_IND_SUM_KEY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY ADD CONSTRAINT CHK_WDI_REGION_IND_COUNT CHECK (COUNTRY_COUNT >= 0)]', 'CHK_WDI_REGION_IND_COUNT');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY ADD CONSTRAINT CHK_WDI_REGION_REC_COUNT CHECK (RECORD_COUNT >= 0)]', 'CHK_WDI_REGION_REC_COUNT');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY ADD CONSTRAINT CHK_WDI_REGION_IND_YEAR CHECK (YEAR IS NULL OR YEAR BETWEEN 1900 AND 2100)]', 'CHK_WDI_REGION_IND_YEAR');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.REGION_INDICATOR_SUMMARY ADD CONSTRAINT CHK_WDI_REGION_IND_MAXMIN CHECK (MAX_VALUE IS NULL OR MIN_VALUE IS NULL OR MAX_VALUE >= MIN_VALUE)]', 'CHK_WDI_REGION_IND_MAXMIN');

    -- TABLE 13: SERIES_TOPIC_COVERAGE
    DBMS_OUTPUT.PUT_LINE('TABLE: SERIES_TOPIC_COVERAGE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE ADD CONSTRAINT PK_WDI_SERIES_TOPIC_COVERAGE PRIMARY KEY (COVERAGE_ID)]', 'PK_WDI_SERIES_TOPIC_COVERAGE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE ADD CONSTRAINT FK_WDI_SERIES_TOPIC_SS FOREIGN KEY (SERIES_CODE) REFERENCES WORLD_BANK_WDI.SERIES_SUMMARY (SERIES_CODE)]', 'FK_WDI_SERIES_TOPIC_SS');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE ADD CONSTRAINT UQ_WDI_SERIES_TOPIC_CODE UNIQUE (SERIES_CODE)]', 'UQ_WDI_SERIES_TOPIC_CODE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE ADD CONSTRAINT CHK_WDI_SERIES_TOPIC_CNTRYS CHECK (TOTAL_COUNTRIES >= 0)]', 'CHK_WDI_SERIES_TOPIC_CNTRYS');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE ADD CONSTRAINT CHK_WDI_SERIES_TOPIC_RECORDS CHECK (TOTAL_RECORDS >= 0)]', 'CHK_WDI_SERIES_TOPIC_RECORDS');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.SERIES_TOPIC_COVERAGE ADD CONSTRAINT CHK_WDI_SERIES_TOPIC_PCT CHECK (DATA_COMPLETENESS_PCT IS NULL OR (DATA_COMPLETENESS_PCT >= 0 AND DATA_COMPLETENESS_PCT <= 100))]', 'CHK_WDI_SERIES_TOPIC_PCT');

    -- TABLE 14: INCOME_GROUP_INDICATOR_PROFILE
    DBMS_OUTPUT.PUT_LINE('TABLE: INCOME_GROUP_INDICATOR_PROFILE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE ADD CONSTRAINT PK_WDI_INC_GRP_IND_PROFILE PRIMARY KEY (PROFILE_ID)]', 'PK_WDI_INC_GRP_IND_PROFILE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE ADD CONSTRAINT UQ_WDI_INC_GRP_IND_KEY UNIQUE (INCOME_GROUP, INDICATOR_CODE, YEAR)]', 'UQ_WDI_INC_GRP_IND_KEY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE ADD CONSTRAINT CHK_WDI_INC_GRP_COUNT CHECK (COUNTRY_COUNT >= 0)]', 'CHK_WDI_INC_GRP_COUNT');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE ADD CONSTRAINT CHK_WDI_INC_GRP_REG_COUNT CHECK (DISTINCT_REGIONS_COUNT IS NULL OR DISTINCT_REGIONS_COUNT >= 0)]', 'CHK_WDI_INC_GRP_REG_COUNT');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE ADD CONSTRAINT CHK_WDI_INC_GRP_YEAR CHECK (YEAR IS NULL OR YEAR BETWEEN 1900 AND 2100)]', 'CHK_WDI_INC_GRP_YEAR');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.INCOME_GROUP_INDICATOR_PROFILE ADD CONSTRAINT CHK_WDI_INC_GRP_MAXMIN CHECK (MAX_VALUE IS NULL OR MIN_VALUE IS NULL OR MAX_VALUE >= MIN_VALUE)]', 'CHK_WDI_INC_GRP_MAXMIN');

    -- TABLE 15: COUNTRY_DATA_QUALITY_AUDIT
    DBMS_OUTPUT.PUT_LINE('TABLE: COUNTRY_DATA_QUALITY_AUDIT');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT PK_WDI_COUNTRY_DATA_QUALITY PRIMARY KEY (AUDIT_ID)]', 'PK_WDI_COUNTRY_DATA_QUALITY');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT FK_WDI_COUNTRY_DQ_CS FOREIGN KEY (COUNTRY_CODE) REFERENCES WORLD_BANK_WDI.COUNTRY_SUMMARY (COUNTRY_CODE)]', 'FK_WDI_COUNTRY_DQ_CS');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT FK_WDI_COUNTRY_DQ_SERIES FOREIGN KEY (SERIES_CODE) REFERENCES WORLD_BANK_WDI.SERIES_SUMMARY (SERIES_CODE) NOVALIDATE]', 'FK_WDI_COUNTRY_DQ_SERIES');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT CHK_WDI_DQ_HAS_FOOTNOTE CHECK (HAS_FOOTNOTE IN ('Y', 'N'))]', 'CHK_WDI_DQ_HAS_FOOTNOTE');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT CHK_WDI_DQ_NULL_FLAG CHECK (NULL_VALUE_FLAG IN ('Y', 'N'))]', 'CHK_WDI_DQ_NULL_FLAG');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT CHK_WDI_DQ_CENSUS_FLAG CHECK (CENSUS_DATA_AVAILABLE IN ('Y', 'N'))]', 'CHK_WDI_DQ_CENSUS_FLAG');
    exec_cst(q'[ALTER TABLE WORLD_BANK_WDI.COUNTRY_DATA_QUALITY_AUDIT ADD CONSTRAINT CHK_WDI_DQ_YEAR CHECK (YEAR IS NULL OR YEAR BETWEEN 1900 AND 2100)]', 'CHK_WDI_DQ_YEAR');

    DBMS_OUTPUT.PUT_LINE(CHR(10) || RPAD('=', 80, '='));
    DBMS_OUTPUT.PUT_LINE('✔ GLOBAL SCRIPT EXECUTION COMPLETED SUCCESSFULLY');
    DBMS_OUTPUT.PUT_LINE(RPAD('=', 80, '='));

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(CHR(10) || RPAD('!', 80, '!'));
        DBMS_OUTPUT.PUT_LINE('FATAL ERROR DURING SCRIPT EXECUTION: ' || SQLERRM);
        DBMS_OUTPUT.PUT_LINE(RPAD('!', 80, '!'));
        ROLLBACK;
        RAISE;
END;

